---
- name: Include vars
  include_vars: vars.yml
  tags: always

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/work"

- name: List up dotfiles to link
  find:
    path: "{{ lookup('env', 'DOTPATH') }}"
    hidden: true
    pattern: .*
    excludes:
      - ".DS_Store"
      - "*.swp"
      - ".gitignore"
  register:
    dotfiles
  tags: symlink

- name: Symlink dotfiles
  file:
    src: "{{ item }}"
    dest: "~/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ dotfiles.files | map(attribute='path') | list }}"
  tags: symlink

- name: Install Python modules
  pip:
    name: "{{ packages | map(attribute='pip') | select('defined') | list }}"
  tags: pip

- when: ansible_os_family == "Darwin"
  block:
    - name: Install Homebrew
      command:
        cmd: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
        creates: /usr/local/bin/brew
      tags: check_brew

    - name: Update Homebrew
      homebrew:
        update_homebrew: true

    - name: Install/Upgrade formulae
      homebrew:
        name: "{{ packages | map(attribute='brew') | select('defined') | list }}"
        upgrade_all: true
      tags: brew_formula

    - name: Install/Upgrade casks
      homebrew_cask:
        name: "{{ packages | map(attribute='cask') | select('defined') | list }}"
        upgrade_all: true
      tags: brew_cask

- name: Install Go
  import_role: name=install_go
  tags: go

- name: Install Go packages
  shell: "go get -v {{ item }}"
  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}/dev/go"
  loop: "{{ packages | map(attribute='go') | select('defined') | list }}"
  register: result
  changed_when: "result.stdout != ''"
  tags: go

- name: Install tmux plugin manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: ~/.tmux/plugins/tpm
  tags: tpm

- name: Install tmux plugins
  shell: "! ~/.tmux/plugins/tpm/bin/install_plugins | grep -v 'Already installed'"
  register: result
  changed_when: "result.stdout != ''"
  tags: tpm

- name: Install snippets
  get_url:
    url: "{{ item }}"
    dest: "{{ lookup('env', 'HOME_LOCAL') }}/bin"
    mode: "u=rwx,g=rx,o=rx"
  loop: "{{ packages | map(attribute='snippet') | select('defined') | list }}"
  tags: snippet

- shell: "cat /etc/shells | grep zsh | tail -1"
  register: zsh_path
  ignore_errors: true
  changed_when: false
  tags: zsh

- name: Install zsh plugins
  command:
    cmd: "zsh -i -c -- '@zinit-scheduler burst'"
    creates: ~/.zinit/plugins
  when: zsh_path is succeeded
  tags: zsh

- name: Change user shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: "{{ zsh_path.stdout }}"
  when: zsh_path is succeeded
  become: true
  tags: zsh

- debug:
    msg: |
      Install zsh and add its path to /etc/shells.
      Then execute `chsh -s /path/to/zsh`.
  when: zsh_path is failed
  tags: zsh

