- name: Disable night mode
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: 'false'

- name: Map Ctrl to CapsLock
  dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps']"

- name: Enable natural scroll on touchpad
  dconf:
    key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
    value: 'true'

- name: Move the window titlebar buttons to left
  dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "'close,minimize,maximize:appmenu'"

- name: Unbind switch-applications (Alt-Tab, Super-Tab)
  dconf:
    key: "{{ item }}"
    value: "'[]'"
  loop:
    - /org/gnome/desktop/wm/keybindings/switch-applications
    - /org/gnome/desktop/wm/keybindings/switch-applications-backward

- name: Bind Alt-Tab and Super-Tab to switch-windows
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: /org/gnome/desktop/wm/keybindings/switch-windows,          value: "['<Super>Tab', '<Alt>Tab']" }
    - { key: /org/gnome/desktop/wm/keybindings/switch-windows-backward, value: "['<Shift><Super>Tab', '<Shift><Alt>Tab']" }

- name: Show battery percentage next to the battery icon on the status bar
  dconf:
    key: /org/gnome/desktop/interface/show-battery-percentage
    value: 'true'

- name: Enable user extensions
  dconf:
    key: /org/gnome/shell/disable-user-extensions
    value: 'false'

- name: Workspaces only on primary display
  dconf:
    key: /org/gnome/mutter/workspaces-only-on-primary
    value: 'true'

- name: Install GNOME extensions
  script:
    cmd: "gnome-shell-extension-cli/gnome-shell-extension-cli install {{ item }}"
    executable: /bin/python3
  register: result
  changed_when: "'Extension already installed' not in result.stderr_lines"
  loop: "{{ extensions }}"
