---
- name: Prevent creating .DS_Store on network drive
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: string
    value: "true"

- name: Don't wait too long before key repeat
  community.general.osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15

- name: Enable text selection on Quick Look
  community.general.osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: yes

- name: Show hidden files on Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: yes

- name: Reduce motion
  community.general.osx_defaults:
    domain: com.apple.universalaccess
    key: reduceMotion
    type: int
    value: 1

- name: Differentiate without colour
  community.general.osx_defaults:
    domain: com.apple.universalaccess
    key: differentiateWithoutColor
    type: int
    value: 1

- name: Disable automatical capitalize
  community.general.osx_defaults:
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: no

# Getting ready for dict_add
# cf. https://github.com/ansible-collections/community.general/pull/3420
# - name: Create shortcuts
#   community.general.osx_defaults:
#     domain: "{{ item.app }}"
#     key: NSUserKeyEquivalents
#     dict_add: "{{ item.menu }}"
#     type: string
#     value: "{{ item.key }}"
#   loop:
#     - app: "com.bitwarden.desktop"
#       menu: "Sync Vault"
#       key: "@s"
