---
- include: linux.yml
  when: ansible_os_family not in ['Darwin', 'Windows']

- include: gnome.yml
  when: lookup('env', 'DESKTOP_SESSION') == 'gnome'

- include: arch.yml
  when: ansible_os_family == 'Archlinux'
