---
- name: Install Docker (macOS)
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: docker
    state: upgraded

- name: Install Docker (Arch Linux)
  when: ansible_os_family == "Archlinux"
  pacman:
    name: docker
    state: latest
  become: true
