---
- name: Install Docker (macOS)
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: docker
    state: upgraded

- when: ansible_os_family == "Archlinux"
  block:
    - name: Install Docker (Arch Linux)
      pacman:
        name: docker
        state: latest
      become: true

    - name: Create user group for Docker
      group:
        name: docker
      become: yes

    - name: Add current user to the group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker
      become: yes

    - name: Activate group changes
      command: newgrp docker
      changed_when: false

    - name: Enable Docker daemon
      systemd:
        name: docker
        enabled: yes
        state: started
      become: yes
