---
- name: Install Docker (macOS)
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: docker
    state: upgraded

- when: ansible_os_family == "Archlinux"
  block:
    - name: Install Docker (Arch Linux)
      pacman:
        name: docker
        state: latest
      become: true

    - name: Enable Docker daemon
      systemd:
        name: docker
        enabled: yes
        state: started
      become: yes
