#!/bin/zsh

case $1 in
  cd )
    repo="$(ghq list | sed -e 's@^github.com/@@' | fzf)"
    [ -z "$repo" ] && return
    cd "$(ghq list --full-path --exact "$repo")"
    ;;

  root )
    cd "$(git rev-parse --show-toplevel)"
    ;;

  * )
    \ghq "$@"
    ;;
esac

