---
- set_fact: dir="~/Library/Fonts"
  when: ansible_os_family == "Darwin"

- set_fact: dir="~/.local/share/fonts"
  when: ansible_os_family == "Archlinux"

- file:
    path: "{{ dir }}"
    state: directory

- name: Install Ricty
  unarchive:
    remote_src: yes
    src: https://rictyfonts.github.io/files/ricty_diminished-4.1.1.tar.gz
    exclude: OFL.txt
    dest: "{{ dir }}"

- name: Install Cica
  unarchive:
    remote_src: yes
    src: https://github.com/miiton/Cica/releases/download/v5.0.1/Cica_v5.0.1_with_emoji.zip
    exclude:
      - COPYRIGHT.txt
      - LICENSE.txt
    dest: "{{ dir }}"
