---
- set_fact: dir="~/Library/Fonts"
  when: ansible_os_family == "Darwin"

- name: Install Ricty
  unarchive:
    remote_src: yes
    src: https://rictyfonts.github.io/files/ricty_diminished-4.1.1.tar.gz
    exclude: OFL.txt
    dest: "{{ dir }}"
