name: Arch Linux

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Setup
        run: |
          useradd dot
          mkdir /home/dot
          chown dot /home/dot
          pacman -Sy --noconfirm sudo git
          echo 'dot ALL=NOPASSWD: ALL' >>/etc/sudoers

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Deploy
        run: sudo -u dot deploy/deploy.sh
        shell: sh
        env:
          CI: 'true'
