name: Setting up new Arch Linux

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Setup
        run: |
          useradd dot
          mkdir /home/dot
          chown dot /home/dot
          pacman -Sy --noconfirm sudo
          echo 'dot ALL=NOPASSWD: ALL' >>/etc/sudoers
          su - dot

      - name: Deploy
        run: curl -sL dot.aiotter.com | bash
        shell: sh
