name: Setting up new Arch Linux

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Setup
        run: |
          useradd dot
          mkdir /home/dot
          chown dot /home/dot
          pacman -Sy --noconfirm sudo git
          echo 'dot ALL=NOPASSWD: ALL' >>/etc/sudoers

      - name: Checkout
        run: git clone "https://github.com/${GITHUB_REPOSITORY}"

      - name: Deploy
        run: sudo -u dot sh -c 'curl -sL dot.aiotter.com | bash'
        shell: sh
        env:
          CI: 'true'
