name: macOS

on: [push]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Deploy
        run: deploy/deploy.sh
