name: Setting up new macOS

on: [push]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy
      run: curl -L dot.aiotter.com | bash

    - name: Initialize zsh
      run: zsh -eo pipefail -ic true

