---
- name: Install Go (macOS)
  when: ansible_os_family == "Darwin"
  homebrew:
    name: go
    state: latest

- name: Install Go (Arch Linux)
  when: ansible_os_family == "Archlinux"
  pacman:
    name: go
    state: latest
  become: true
